[manager]
prepend_keymap = [
  { on = "T", run = "plugin hide-preview", desc = "Hide or show preview" },
  { on = [ "c", "m" ], run = "plugin chmod", desc = "Chmod on selected files" },
  { on = ["F"], run = "plugin jump-to-char", desc = "Jump to char" },
  { on = [ "E" ], run = "plugin eza-preview",  desc = "Toggle tree/list dir preview" },
  { on = [ "-" ], run = "plugin eza-preview --args='--inc-level'", desc = "Increment tree level" },
  { on = [ "_" ], run = "plugin eza-preview --args='--dec-level'", desc = "Decrement tree level" },
  { on = [ "$" ], run = "plugin eza-preview --args='--toggle-follow-symlinks'", desc = "Toggle tree follow symlinks" },
  { on = [ "c", "a" ], run = "plugin compress", desc = "Archive selected files" },
  { on = [ ",", "," ], run  = "plugin what-size", desc = "Calc size of selection or cwd" },
  { on = ["<C-d>"], run  = "plugin diff", desc = "Diff the selected with the hovered file"},
  { on = ["<A-y>"], run = "plugin copy-file-contents", desc = "Copy contents of file"},
  { on = ["<C-y>"], run = ["plugin system-clipboard"]},
  { on = ["l"], run  = "plugin smart-enter", desc = "Enter the child directory, or open the file"},
]
